// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYiH2OHp06-XivuqxnjaZq03YXWovO0k',
    appId: '1:169977822730:web:e49f6dd86b3ad418d4e9f3',
    messagingSenderId: '169977822730',
    projectId: 'ulearningapp-25de0',
    authDomain: 'ulearningapp-25de0.firebaseapp.com',
    storageBucket: 'ulearningapp-25de0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9BU_y9iCtv8-6njlBYlqLJL0beDcs1Hk',
    appId: '1:169977822730:android:182f60acfdb82514d4e9f3',
    messagingSenderId: '169977822730',
    projectId: 'ulearningapp-25de0',
    storageBucket: 'ulearningapp-25de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9TYfAtRezClAi59makIt37JFPvxbck0',
    appId: '1:169977822730:ios:c21d3489a53f00d9d4e9f3',
    messagingSenderId: '169977822730',
    projectId: 'ulearningapp-25de0',
    storageBucket: 'ulearningapp-25de0.appspot.com',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX9TYfAtRezClAi59makIt37JFPvxbck0',
    appId: '1:169977822730:ios:a7751d9d3d5cffbfd4e9f3',
    messagingSenderId: '169977822730',
    projectId: 'ulearningapp-25de0',
    storageBucket: 'ulearningapp-25de0.appspot.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
